### ISSUE TITLE
Definition breaks

### ISSUE THREAD

**Issue by jiggo** [shiftonelabs/laravel-nomad#1]
Hi,

on this call
    `$table->passthru('bit(32)', 'availability', 'B\'11111111111111111111111111111111\'::"bit"');`

the query breaks in this way
    `"availability" B'11111111111111111111111111111111'::"bit" not null,`

As you can see type is not set in query instruction.

**Comment by patrickcarlohickman** [comment]
Please correct me if I'm wrong, but it looks like you're trying to use the third parameter to assign a default value. The third parameter, when provided, will be used as the actual definition for the field. When the third parameter is passed, the first parameter is completely ignored.

For example:

```
$table->passthru('string', 'email', 'varchar(255)')
```

In the above example, the 'string' parameter is ignored, and the field is defined as 'varchar(255)'.

If you want to define a default value, you can either do it directly in the definition, or you can still use the fluent `->default()` method. A couple examples for your use case:

```
// define the default in your field defintion
$table->passthru('bit(32)', 'availability', 'bit(32) default B\'11111111111111111111111111111111\'::"bit"');

// same as above, just showing that the first parameter is
// informational only when the third parameter is given
$table->passthru('bit', 'availability', 'bit(32) default B\'11111111111111111111111111111111\'::"bit"');

// use fluent syntax to define default
// DB::raw needed to avoid extra quoting
$table->passthru('bit(32)', 'availability')->default(DB::raw('B\'11111111111111111111111111111111\'::"bit"'));
```

Let me know if this solves the issue. Thanks!

**Comment by jiggo** [comment]
@patrickcarlohickman You're totally right, my fault.

Sry.

**Comment by patrickcarlohickman** [comment]
@jiggo Not a problem. Thanks for using the package!
